'use client';
import { useEffect, useState } from 'react';
import { getTeamColor, isWhiteTeam } from '../lib/constants';
import LoadingState, { ErrorState } from '../components/LoadingState';
import FilterPills from '../components/FilterPills';
import DataFreshness from '../components/DataFreshness';

// Sheet: EstadisticasJugadores  (generated by the Apps Script crearEstadisticasJugadores)
// Block layout per team: 1 blank + 1 title ("Equipo: ...") + 2 header rows + 12 player rows + blank
// Teams are found dynamically by scanning for "Equipo:" title rows.
//
// Column mapping (0-indexed):
//   A  (0)     = Jugador
//   B-K (1-10) = P1 F1..F10  (yellow)
//   L  (11)    = Suma P1      (green)
//   M-V(12-21) = P2 F1..F10  (blue)
//   W  (22)    = Suma P2      (green)
//   X-AG(23-32)= P3 F1..F10  (pink)
//   AH (33)    = Suma P3      (green)
//   AI (34)    = Subtotal     (brick/orange)

const SPREADSHEET_ID = '1JF2vVbrnMYTMC3WrOVVv-vkTICBxh06S0t-40cyPIo0';

async function fetchSheetRows(sheet: string, range: string): Promise<string[][]> {
  const url =
    `https://docs.google.com/spreadsheets/d/${SPREADSHEET_ID}/gviz/tq` +
    `?sheet=${encodeURIComponent(sheet)}&range=${encodeURIComponent(range)}&tqx=out:json&headers=0`;
  const res = await fetch(url);
  if (!res.ok) throw new Error(`HTTP ${res.status}`);
  const text = await res.text();
  const match = text.match(/google\.visualization\.Query\.setResponse\((\{[\s\S]*\})\)/);
  if (!match) throw new Error('Formato de respuesta inesperado');
  const payload = JSON.parse(match[1]) as {
    status: string;
    table: { cols: unknown[]; rows: Array<{ c: Array<{ v: unknown } | null> | null } | null> };
  };
  if (payload.status !== 'ok') throw new Error(`Estado: ${payload.status}`);
  const { cols, rows } = payload.table;
  const numCols = cols.length;
  return rows.map(row => {
    const cells: string[] = new Array(numCols).fill('');
    if (row?.c) {
      row.c.forEach((cell, i) => {
        if (cell?.v != null) cells[i] = String(cell.v);
      });
    }
    return cells;
  });
}

const FECHAS_LABELS = ['F1','F2','F3','F4','F5','F6','F7','F8','F9','F10'];

const EQUIPOS_NOMBRES = [
  'Miami Heat',
  'Brooklyn Nets',
  'Boston Celtics',
  'Oklahoma City Thunder',
  'Los Angeles Lakers',
  'Toronto Raptors',
];

interface JugadorDetalle {
  nombre: string;
  p1: number[];
  p2: number[];
  p3: number[];
  sumaP1: number;
  sumaP2: number;
  sumaP3: number;
  subtotal: number;
}

interface EquipoData {
  nombre: string;
  jugadores: JugadorDetalle[];
}

function parseNum(v: string | undefined): number {
  if (v === undefined || v === '') return 0;
  const n = parseFloat(v);
  return isNaN(n) ? 0 : Math.round(n);
}

// Colors that work in both dark and light mode
// hdr = section heading background  |  bg = data cell background
// txt = section heading text (always white)
// val = value text in data rows (adapted per theme below)
// bdr = left border of section
function makeColors(light: boolean) {
  return {
    p1: {
      bg:    light ? 'rgba(180,145,0,0.09)'  : 'rgba(255,220,0,0.13)',
      hdr:   light ? 'rgba(150,120,0,0.80)'  : 'rgba(160,140,0,0.60)',
      bdr:   light ? 'rgba(150,120,0,0.55)'  : 'rgba(220,200,0,0.45)',
      txt:   '#ffffff',
      val:   light ? '#7a5c00'               : '#ffe450',
      label: 'PUNTOS DE 1',
    },
    p2: {
      bg:    light ? 'rgba(20,80,200,0.09)'  : 'rgba(60,130,255,0.13)',
      hdr:   light ? 'rgba(20,70,190,0.80)'  : 'rgba(40,80,200,0.60)',
      bdr:   light ? 'rgba(20,70,190,0.55)'  : 'rgba(80,140,255,0.45)',
      txt:   '#ffffff',
      val:   light ? '#0e3f9e'               : '#a0d4ff',
      label: 'PUNTOS DE 2',
    },
    p3: {
      bg:    light ? 'rgba(190,20,110,0.09)' : 'rgba(240,60,160,0.13)',
      hdr:   light ? 'rgba(170,15,95,0.80)'  : 'rgba(180,30,110,0.60)',
      bdr:   light ? 'rgba(170,15,95,0.55)'  : 'rgba(230,70,160,0.45)',
      txt:   '#ffffff',
      val:   light ? '#960058'               : '#ffaadd',
      label: 'PUNTOS DE 3',
    },
    suma: {
      bg:    light ? 'rgba(10,150,50,0.09)'  : 'rgba(50,210,90,0.13)',
      hdr:   light ? 'rgba(10,130,45,0.80)'  : 'rgba(30,160,70,0.60)',
      bdr:   light ? 'rgba(10,130,45,0.55)'  : 'rgba(60,210,100,0.45)',
      txt:   '#ffffff',
      val:   light ? '#0a5a20'               : '#80ff98',
    },
    sub: {
      bg:    light ? 'rgba(185,100,0,0.09)'  : 'rgba(230,140,30,0.15)',
      hdr:   light ? 'rgba(160,85,0,0.80)'   : 'rgba(190,110,20,0.65)',
      bdr:   light ? 'rgba(160,85,0,0.55)'   : 'rgba(230,150,40,0.50)',
      txt:   '#ffffff',
      val:   light ? '#7a3f00'               : '#ffc050',
      label: 'SUBTOTAL',
    },
    name: {
      bg:  'var(--color-bg-header)',
      bdr: light ? 'rgba(0,0,0,0.12)' : 'rgba(255,255,255,0.10)',
    },
  };
}

export default function EstadisticaJugadores() {
  const [equipos, setEquipos]           = useState<EquipoData[]>([]);
  const [equipoActivo, setEquipoActivo] = useState(0);
  const [loading, setLoading]           = useState(true);
  const [error, setError]               = useState(false);
  const [lastUpdated, setLastUpdated]   = useState<Date | null>(null);
  const [isLight, setIsLight]           = useState(false);
  const [fechasDates, setFechasDates]   = useState<string[]>(Array(10).fill(''));

  useEffect(() => {
    const check = () => setIsLight(document.documentElement.classList.contains('light'));
    check();
    const obs = new MutationObserver(check);
    obs.observe(document.documentElement, { attributes: true, attributeFilter: ['class'] });
    return () => obs.disconnect();
  }, []);

  const fetchData = () => {
    setLoading(true);
    setError(false);
    fetchSheetRows('EstadisticasJugadores', 'A1:AI200')
      .then(rows => {
        if (rows.length < 2) { setError(true); setLoading(false); return; }
        // Dynamically find team title rows ("Equipo: ...") instead of
        // relying on hardcoded row numbers that depend on gviz offset
        const teamTitleIndices: number[] = [];
        rows.forEach((r, i) => {
          if ((r[0] || '').trim().toLowerCase().startsWith('equipo')) {
            teamTitleIndices.push(i);
          }
        });

        // Extract date labels from header rows (between first title and first player)
        if (teamTitleIndices.length > 0) {
          const start = teamTitleIndices[0] + 1;
          const end = Math.min(start + 4, teamTitleIndices[1] ?? rows.length);
          for (let i = start; i < end; i++) {
            const row = rows[i];
            // Look for a row whose columns 1-10 contain date-like values (with "/")
            if (row.slice(1, 11).some(c => (c || '').includes('/'))) {
              setFechasDates(row.slice(1, 11).map(c => (c || '').trim()));
              break;
            }
          }
        }

        const result: EquipoData[] = EQUIPOS_NOMBRES.map((nombre, teamIdx) => {
          const titleIdx = teamTitleIndices[teamIdx];
          if (titleIdx == null) {
            return { nombre, jugadores: [] };
          }
          // Read all rows from after this title to the next team's title
          const nextTitle = teamTitleIndices[teamIdx + 1] ?? rows.length;
          const blockRows = rows.slice(titleIdx + 1, nextTitle);
          // Keep only rows with an actual player name (filters out headers,
          // blank rows, "Jugador" sub-headers, and formula-only rows)
          const jugadores: JugadorDetalle[] = blockRows
            .filter(r => {
              const name = (r[0] || '').trim();
              if (name === '') return false;
              const lower = name.toLowerCase();
              return !lower.startsWith('equipo') && lower !== 'jugador';
            })
            .slice(0, 12)
            .map(r => ({
              nombre: (r[0] || '').trim(),
              p1:       [1,2,3,4,5,6,7,8,9,10].map(i => parseNum(r[i])),
              sumaP1:   parseNum(r[11]),
              p2:       [12,13,14,15,16,17,18,19,20,21].map(i => parseNum(r[i])),
              sumaP2:   parseNum(r[22]),
              p3:       [23,24,25,26,27,28,29,30,31,32].map(i => parseNum(r[i])),
              sumaP3:   parseNum(r[33]),
              subtotal: parseNum(r[34]),
            }));
          return { nombre, jugadores };
        });
        setEquipos(result);
        setLastUpdated(new Date());
        setLoading(false);
      })
      .catch(() => { setError(true); setLoading(false); });
  };

  useEffect(() => {
    fetchData();
    // Auto-refresh every 5 minutes so new players added in Google Sheets appear automatically
    const interval = setInterval(fetchData, 5 * 60 * 1000);
    return () => clearInterval(interval);
  }, []);

  const C = makeColors(isLight);
  const eq = equipos[equipoActivo];

  return (
    <div className="animate-fade-in">
      <div className="px-4 md:px-6 pt-4 flex items-center justify-between">
        <h2 className="text-sm text-text-muted uppercase tracking-widest flex items-center gap-2">
          <span className="w-1 h-4 bg-gold rounded-full" />
          Estadística Jugadores
        </h2>
        <DataFreshness lastUpdated={lastUpdated} onRefresh={fetchData} loading={loading} />
      </div>

      <div className="px-4 md:px-6 py-4">
        <FilterPills
          items={equipos.map((e, i) => ({
            key: String(i),
            label: e.nombre,
            color: getTeamColor(e.nombre),
          }))}
          active={String(equipoActivo)}
          onChange={(key) => setEquipoActivo(Number(key))}
          variant="outline"
        />
      </div>

      <div className="px-4 md:px-6 pb-8">
        {loading ? (
          <LoadingState message="Cargando estadísticas de jugadores..." variant="skeleton" rows={8} />
        ) : error ? (
          <ErrorState onRetry={fetchData} />
        ) : eq ? (
          <div className="glass-card rounded-xl overflow-hidden">

            {/* Team header */}
            <div
              className="px-5 py-4 flex items-center gap-2.5"
              style={{
                background: isWhiteTeam(eq.nombre) ? '#FFFFFF' : getTeamColor(eq.nombre) + '20',
                borderBottom: `2px solid ${getTeamColor(eq.nombre)}`,
              }}
            >
              <div
                className="w-3 h-3 rounded-full shrink-0"
                style={{
                  background: getTeamColor(eq.nombre),
                  outline: isWhiteTeam(eq.nombre) ? '1.5px solid #CCCCCC' : 'none',
                }}
              />
              <span
                className="font-bold text-base"
                style={{ color: isWhiteTeam(eq.nombre) ? '#111111' : 'var(--color-text-primary)' }}
              >
                {eq.nombre}
              </span>
              <span className="text-xs text-text-muted ml-2">{eq.jugadores.filter(j => j.nombre.trim() !== '').length} jugadores</span>
            </div>

            {/* Table */}
            <div className="overflow-x-auto">
              <table
                className="w-full text-[11px] border-collapse"
                style={{ minWidth: '1100px' }}
              >
                <thead>
                  {/* Row 1: section labels */}
                  <tr>
                    <th
                      rowSpan={2}
                      className="text-center align-middle px-3 py-3 font-bold sticky left-0 z-20 text-[15px] uppercase tracking-wide"
                      style={{ background: C.name.bg, minWidth: '160px', borderRight: `1px solid ${C.name.bdr}`, color: '#ffffff' }}
                    >
                      Jugador
                    </th>

                    {/* PUNTOS DE 1 */}
                    <th colSpan={11} className="text-center py-2 font-bold tracking-widest text-[11px] uppercase"
                      style={{ background: C.p1.hdr, borderLeft: `3px solid ${C.p1.bdr}`, color: C.p1.txt }}>
                      {C.p1.label}
                    </th>
                    {/* PUNTOS DE 2 */}
                    <th colSpan={11} className="text-center py-2 font-bold tracking-widest text-[11px] uppercase"
                      style={{ background: C.p2.hdr, borderLeft: `3px solid ${C.p2.bdr}`, color: C.p2.txt }}>
                      {C.p2.label}
                    </th>
                    {/* PUNTOS DE 3 */}
                    <th colSpan={11} className="text-center py-2 font-bold tracking-widest text-[11px] uppercase"
                      style={{ background: C.p3.hdr, borderLeft: `3px solid ${C.p3.bdr}`, color: C.p3.txt }}>
                      {C.p3.label}
                    </th>
                    {/* SUBTOTAL */}
                    <th rowSpan={2} className="text-center px-2 py-2 font-bold tracking-widest text-[11px] uppercase"
                      style={{ background: C.sub.hdr, borderLeft: `3px solid ${C.sub.bdr}`, color: C.sub.txt, minWidth: '62px' }}>
                      {C.sub.label}
                    </th>
                  </tr>

                  {/* Row 2: fecha labels per section */}
                  <tr>
                    {/* P1 F1-F10 */}
                    {FECHAS_LABELS.map((lbl, i) => (
                      <th key={`hP1-${i}`} className="text-center px-0 py-1 font-medium"
                        style={{
                          background: C.p1.hdr,
                          borderLeft: i === 0 ? `3px solid ${C.p1.bdr}` : `1px solid rgba(255,255,255,0.08)`,
                          color: C.p1.txt,
                          minWidth: '32px',
                        }}>
                        {lbl}
                        <div style={{ fontSize: '8px', opacity: 0.75 }}>{fechasDates[i]}</div>
                      </th>
                    ))}
                    {/* Σ P1 */}
                    <th className="text-center px-1 py-1 font-bold"
                      style={{ background: C.suma.hdr, borderLeft: `2px solid ${C.suma.bdr}`, color: C.suma.txt, minWidth: '46px' }}>
                      Σ P1
                    </th>

                    {/* P2 F1-F10 */}
                    {FECHAS_LABELS.map((lbl, i) => (
                      <th key={`hP2-${i}`} className="text-center px-0 py-1 font-medium"
                        style={{
                          background: C.p2.hdr,
                          borderLeft: i === 0 ? `3px solid ${C.p2.bdr}` : `1px solid rgba(255,255,255,0.08)`,
                          color: C.p2.txt,
                          minWidth: '32px',
                        }}>
                        {lbl}
                        <div style={{ fontSize: '8px', opacity: 0.75 }}>{fechasDates[i]}</div>
                      </th>
                    ))}
                    {/* Σ P2 */}
                    <th className="text-center px-1 py-1 font-bold"
                      style={{ background: C.suma.hdr, borderLeft: `2px solid ${C.suma.bdr}`, color: C.suma.txt, minWidth: '46px' }}>
                      Σ P2
                    </th>

                    {/* P3 F1-F10 */}
                    {FECHAS_LABELS.map((lbl, i) => (
                      <th key={`hP3-${i}`} className="text-center px-0 py-1 font-medium"
                        style={{
                          background: C.p3.hdr,
                          borderLeft: i === 0 ? `3px solid ${C.p3.bdr}` : `1px solid rgba(255,255,255,0.08)`,
                          color: C.p3.txt,
                          minWidth: '32px',
                        }}>
                        {lbl}
                        <div style={{ fontSize: '8px', opacity: 0.75 }}>{fechasDates[i]}</div>
                      </th>
                    ))}
                    {/* Σ P3 */}
                    <th className="text-center px-1 py-1 font-bold"
                      style={{ background: C.suma.hdr, borderLeft: `2px solid ${C.suma.bdr}`, color: C.suma.txt, minWidth: '46px' }}>
                      Σ P3
                    </th>
                  </tr>
                </thead>

                <tbody>
                  {eq.jugadores.map((j, rowIdx) => {
                    const rowBg = rowIdx % 2 === 0 ? 'var(--color-bg-secondary)' : 'var(--color-bg-card)';
                    return (
                      <tr key={rowIdx} className="border-b border-border-subtle table-row-hover">
                        {/* Name */}
                        <td className="px-3 py-2 font-semibold text-[12px] sticky left-0 z-10"
                          style={{ background: rowBg, borderRight: `1px solid ${C.name.bdr}`, color: 'var(--color-text-primary)' }}>
                          {j.nombre}
                        </td>

                        {/* P1 F1-F10 */}
                        {j.p1.map((val, i) => (
                          <td key={`p1-${i}`} className="text-center px-0 py-2"
                            style={{ background: C.p1.bg, borderLeft: i === 0 ? `3px solid ${C.p1.bdr}` : `1px solid rgba(255,255,255,0.04)` }}>
                            {val > 0
                              ? <span style={{ color: C.p1.val, fontWeight: 700 }}>{val}</span>
                              : <span style={{ opacity: 0.20, color: 'var(--color-text-primary)' }}>-</span>}
                          </td>
                        ))}
                        {/* Σ P1 */}
                        <td className="text-center px-1 py-2 font-bold"
                          style={{ background: C.suma.bg, borderLeft: `2px solid ${C.suma.bdr}` }}>
                          {j.sumaP1 > 0
                            ? <span style={{ color: C.suma.val, fontWeight: 700 }}>{j.sumaP1}</span>
                            : <span style={{ opacity: 0.20, color: 'var(--color-text-primary)' }}>-</span>}
                        </td>

                        {/* P2 F1-F10 */}
                        {j.p2.map((val, i) => (
                          <td key={`p2-${i}`} className="text-center px-0 py-2"
                            style={{ background: C.p2.bg, borderLeft: i === 0 ? `3px solid ${C.p2.bdr}` : `1px solid rgba(255,255,255,0.04)` }}>
                            {val > 0
                              ? <span style={{ color: C.p2.val, fontWeight: 700 }}>{val}</span>
                              : <span style={{ opacity: 0.20, color: 'var(--color-text-primary)' }}>-</span>}
                          </td>
                        ))}
                        {/* Σ P2 */}
                        <td className="text-center px-1 py-2 font-bold"
                          style={{ background: C.suma.bg, borderLeft: `2px solid ${C.suma.bdr}` }}>
                          {j.sumaP2 > 0
                            ? <span style={{ color: C.suma.val, fontWeight: 700 }}>{j.sumaP2}</span>
                            : <span style={{ opacity: 0.20, color: 'var(--color-text-primary)' }}>-</span>}
                        </td>

                        {/* P3 F1-F10 */}
                        {j.p3.map((val, i) => (
                          <td key={`p3-${i}`} className="text-center px-0 py-2"
                            style={{ background: C.p3.bg, borderLeft: i === 0 ? `3px solid ${C.p3.bdr}` : `1px solid rgba(255,255,255,0.04)` }}>
                            {val > 0
                              ? <span style={{ color: C.p3.val, fontWeight: 700 }}>{val}</span>
                              : <span style={{ opacity: 0.20, color: 'var(--color-text-primary)' }}>-</span>}
                          </td>
                        ))}
                        {/* Σ P3 */}
                        <td className="text-center px-1 py-2 font-bold"
                          style={{ background: C.suma.bg, borderLeft: `2px solid ${C.suma.bdr}` }}>
                          {j.sumaP3 > 0
                            ? <span style={{ color: C.suma.val, fontWeight: 700 }}>{j.sumaP3}</span>
                            : <span style={{ opacity: 0.20, color: 'var(--color-text-primary)' }}>-</span>}
                        </td>

                        {/* Subtotal */}
                        <td className="text-center px-2 py-2 text-[13px]"
                          style={{ background: C.sub.bg, borderLeft: `3px solid ${C.sub.bdr}` }}>
                          {j.subtotal > 0
                            ? <span style={{ color: C.sub.val, fontWeight: 700 }}>{j.subtotal}</span>
                            : <span style={{ opacity: 0.20, color: 'var(--color-text-primary)' }}>-</span>}
                        </td>
                      </tr>
                    );
                  })}
                </tbody>

                {/* Totals row */}
                <tfoot>
                  <tr style={{ background: 'var(--color-bg-header)' }}>
                    <td className="px-3 py-3 font-bold text-[13px] sticky left-0 z-10"
                      style={{ background: 'var(--color-bg-header)', color: 'var(--color-gold)', borderRight: `1px solid ${C.name.bdr}` }}>
                      TOTAL
                    </td>

                    {/* P1 totals */}
                    {[0,1,2,3,4,5,6,7,8,9].map(i => {
                      const sum = eq.jugadores.reduce((s, j) => s + (j.p1[i] || 0), 0);
                      return (
                        <td key={`tP1-${i}`} className="text-center px-0 py-3 font-bold"
                          style={{ background: C.p1.hdr, borderLeft: i === 0 ? `3px solid ${C.p1.bdr}` : `1px solid rgba(255,255,255,0.08)`, color: C.p1.txt }}>
                          {sum || <span style={{ opacity: 0.4 }}>-</span>}
                        </td>
                      );
                    })}
                    <td className="text-center px-1 py-3 font-bold"
                      style={{ background: C.suma.hdr, borderLeft: `2px solid ${C.suma.bdr}`, color: C.suma.txt }}>
                      {eq.jugadores.reduce((s, j) => s + j.sumaP1, 0) || <span style={{ opacity: 0.4 }}>-</span>}
                    </td>

                    {/* P2 totals */}
                    {[0,1,2,3,4,5,6,7,8,9].map(i => {
                      const sum = eq.jugadores.reduce((s, j) => s + (j.p2[i] || 0), 0);
                      return (
                        <td key={`tP2-${i}`} className="text-center px-0 py-3 font-bold"
                          style={{ background: C.p2.hdr, borderLeft: i === 0 ? `3px solid ${C.p2.bdr}` : `1px solid rgba(255,255,255,0.08)`, color: C.p2.txt }}>
                          {sum || <span style={{ opacity: 0.4 }}>-</span>}
                        </td>
                      );
                    })}
                    <td className="text-center px-1 py-3 font-bold"
                      style={{ background: C.suma.hdr, borderLeft: `2px solid ${C.suma.bdr}`, color: C.suma.txt }}>
                      {eq.jugadores.reduce((s, j) => s + j.sumaP2, 0) || <span style={{ opacity: 0.4 }}>-</span>}
                    </td>

                    {/* P3 totals */}
                    {[0,1,2,3,4,5,6,7,8,9].map(i => {
                      const sum = eq.jugadores.reduce((s, j) => s + (j.p3[i] || 0), 0);
                      return (
                        <td key={`tP3-${i}`} className="text-center px-0 py-3 font-bold"
                          style={{ background: C.p3.hdr, borderLeft: i === 0 ? `3px solid ${C.p3.bdr}` : `1px solid rgba(255,255,255,0.08)`, color: C.p3.txt }}>
                          {sum || <span style={{ opacity: 0.4 }}>-</span>}
                        </td>
                      );
                    })}
                    <td className="text-center px-1 py-3 font-bold"
                      style={{ background: C.suma.hdr, borderLeft: `2px solid ${C.suma.bdr}`, color: C.suma.txt }}>
                      {eq.jugadores.reduce((s, j) => s + j.sumaP3, 0) || <span style={{ opacity: 0.4 }}>-</span>}
                    </td>

                    {/* Subtotal total */}
                    <td className="text-center px-2 py-3 font-bold text-[14px]"
                      style={{ background: C.sub.hdr, borderLeft: `3px solid ${C.sub.bdr}`, color: C.sub.txt }}>
                      {eq.jugadores.reduce((s, j) => s + j.subtotal, 0) || <span style={{ opacity: 0.4 }}>-</span>}
                    </td>
                  </tr>
                </tfoot>
              </table>
            </div>
          </div>
        ) : null}
      </div>
    </div>
  );
}
